version: '3.8'

services:
  frontend:
    image: vos-fe
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vos-fe
    ports:
      - "3000:80"    
    restart: unless-stopped
